/**
 * Build script for FileToMarkdown viewer
 * 
 * This script will combine the individual module files into a single bundle.js file.
 * To use: 
 * 1. Install Node.js
 * 2. Run: node build.js
 */

const fs = require('fs');
const path = require('path');

// Files to include in the bundle
const files = [
    'utils/constants.js',
    'utils/domUtils.js',
    'components/BaseComponent.js',
    'utils/fileManager.js',
    'components/FileList.js',
    'utils/renderer.js',
    'app.js'  // Main app file (to be created)
];

// Output bundle file
const bundlePath = path.join(__dirname, 'bundle.js');

// Create the bundle
let bundleContent = `// FileToMarkdown Viewer Bundle
// Generated on ${new Date().toISOString()}
// DO NOT EDIT THIS FILE DIRECTLY - EDIT THE SOURCE FILES INSTEAD

`;

// Function to process a file and extract its exported content
function processFile(filePath) {
    console.log(`Processing ${filePath}...`);
    const content = fs.readFileSync(path.join(__dirname, filePath), 'utf8');
    
    // Remove import statements
    let processedContent = content.replace(/import .* from .*/g, '');
    
    // Convert export statements to global variables
    processedContent = processedContent.replace(/export (const|let|var|class) (\w+)/g, '$1 $2');
    processedContent = processedContent.replace(/export default (\w+)/g, '// export $1');
    
    return processedContent;
}

// Process each file
files.forEach(file => {
    try {
        bundleContent += `\n// File: ${file}\n`;
        bundleContent += processFile(file);
        bundleContent += '\n';
    } catch (err) {
        console.error(`Error processing ${file}: ${err.message}`);
    }
});

// Add exports at the end
bundleContent += `
// Export all modules for global use
window.FileManager = FileManager;
window.FileList = FileList;
window.DOMUtils = DOMUtils;
window.BrowserRenderer = BrowserRenderer;
window.FileToMarkdownViewer = FileToMarkdownViewer;
`;

// Write the bundle file
fs.writeFileSync(bundlePath, bundleContent);
console.log(`Bundle created at ${bundlePath}`); 